### ISSUE TITLE
3440x1440 screen resolution support

### ISSUE THREAD

**Issue by chatoune** [HaikuArchives/VMwareAddons#11]
Hi,

Here is a modification in order to support such a resolution natively into VMWare.

In the source file VMwareAddons/vmware_video/accelerant/ProposeDisplayMode.c, add the following screen definition.
 { { 319750, 3440, 3488, 3520, 3600, 1440, 1443, 1453, 1481, 0 }, B_RGB32_LITTLE, 3440, 1440, 0, 0, MODE_FLAGS }, /* 3440x1440@60 Hz - Reduced Blanking */

Regards,

Eddy

**Comment by humdingerb** [comment]
Thanks Eddy.
