### ISSUE TITLE
video driver doesn't get loaded on x86_64

### ISSUE THREAD

**Issue by diversys** [HaikuArchives/VMwareAddons#13]
Probably linking flags are wrong.

grep vmware /var/log/syslog

```KERN: Could not load kernel add-on "/boot/system/add-ons/kernel/drivers/dev/graphics/vmware": Bad data```

**Comment by thdankert** [comment]
I've looked a bit deeper into this. When compiling on x86_64, the vmware driver always links to `_KERNEL_`, which in turn requires `linkhack.so` to be available to the runtime_loader.

On my system (freshly installed R1/Beta1) the library is only available in source form, and from the comments in the Jamfile it is only used to trick the linker into thinking that the kernel was build with GCC 2.95. (It uses a custom .comment section for that).
However the `_KERNEL_` does not contain any .comment section, and the runtime_loader will not load it on x86_64.

```
runtime_loader: /boot/system/develop/lib/_KERNEL_: Could not find .comment section
runtime_loader: /boot/system/develop/lib/_KERNEL_: Failed to get gcc version.
runtime_loader: Cannot open file /var/lib/buildbot/workers/haiku/haiku-repository-x86_64/generated/objects/haiku/x86_64/release/system/kernel/linkhack.so: No such file or directory
```

**Comment by korli** [comment]
@thdankert makes little sense, the runtime_loader doesn't load kernel drivers.

**Comment by thdankert** [comment]
> @thdankert makes little sense, the runtime_loader doesn't load kernel drivers.

My bad, then I did not understand driver loading correctly (I used https://www.haiku-os.org/legacy-docs/writing-video-card-drivers/03-kernel-driver/ as a reference).
How are dynamically linked drivers handled then? At some point the kernel would have to resolve the dependencies.

**Comment by korli** [comment]
I don't think dynamically linked drivers are supported (there are module dependencies though).

**Comment by volo-droid** [comment]
@diversys I believe this issue is obsolete now

**Comment by diversys** [comment]
Indeed!
