### ISSUE TITLE
Problems when loading kernel add-on

### ISSUE THREAD

**Issue by Zotyamester** [HaikuArchives/VMwareAddons#22]
I tried to load the drivers in the usual way with linking, but it did not work.

**Comment by Zotyamester** [comment]
KERN: driver "vmwfs" added
KERN: devfs: "vmwfs" api_version missing
KERN: devfs: "vmwfs" mandatory driver symbol(s) missing!
KERN: driver "vmwfs" removed

**Comment by volo-droid** [comment]
@Zotyamester This has been fixed in 1.2.2

cc @diversys
