### ISSUE TITLE
Can no longer boot w/1.2.1

### ISSUE THREAD

**Issue by asmaloney** [HaikuArchives/VMwareAddons#30]
Not 100% sure it's VMWareAddons since I just ran the updater on everything, but I see `AccelerantHWInterface` in the stack trace which may be related to recent changes? When booting, it gets to the last icon and then crashes.

(I know nothing of hardware interfaces, so I could be totally off here.)

Here's a screen grab of the panic:

<img width="1205" alt="Screen Shot 2021-08-25 at 18 01 18 PM" src="https://user-images.githubusercontent.com/391371/130870586-c0c7fb1e-dbd8-4ad2-8f7c-768a06c83585.png">

I see in #25 the following:
```cpp
status_t GET_ACCELERANT_DEVICE_INFO(accelerant_device_info * adi) 
{
	/* no info on version is provided, so presumably this is for my info */
	adi->version = 1;
...
```

Is `adi` guaranteed to be non-null?

Not sure how to get back to a bootable system... 😄

**Comment by fabianmu** [comment]
Same error here. Running on VMware Fusion Player Version 12.1.2 (17964953) on Mac.

**Comment by Coldfirex** [comment]
More info here: https://github.com/haikuports/haikuports/issues/6161

**Comment by Coldfirex** [comment]
If someone could advise me on what to do with the generated files after making some local source changes, I could test out if changing the B_READ -> B_KERNEL_READ helps or not.

**Comment by fabianmu** [comment]
Is there a way to downgrade or at least download an older version of the package?
